config/routes.rb
Directory::Application.routes.draw do

  resources :feedbacks, path: 'feedback', only: :create do
    get :thanks, on: :collection
  end
  resources :faculty, only: [:index]
  resources :people, only: [:show]
  resources :departments, path: 'offices-services', only: [:show]
  resources :groups, only: [:show]

  get "/search", to: "searches#search"
  get "/people" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'person'}).to_query}" }
  get "/departments" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'department'}).to_query}" }
  get "/offices-services" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'department'}).to_query}" }
  get "/groups" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'group'}).to_query}" }


  root to: 'searches#landing'

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [200, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :logout

  # catch all so we can handle routing errors our own way.
  get "*path", to: "application#routing_error", via: :all
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # We don't need to authorize with pundit for these actions.
  #  Anyone can see these pages and SearchQuery limits the results by user role.
  #  These get skipped over verify_authorized in the application_controller.

  def landing
  end

  def search
    search_query = SearchQuery.new(params[:q], facets: facet_types, search_params: params, current_user: current_user, page: params[:page], limit: Settings.pagination_limit)
    results = search_query.execute

    @results_count = results['hits']['total']
    @pages_count = (@results_count / Settings.pagination_limit.to_f).ceil
    @results = results['hits']['hits'] # these get turned into SearchResults in the view/helper
    @facets = filter_facet_affiliations(results['facets'])
  end


  private

  def facet_types
    ['_type', 'affiliations']
  end

  def filter_facet_affiliations(facets)
    permitted_affiliations = UserPermissables.new(current_user).affiliations

    facets["affiliations"]["terms"] = facets["affiliations"]["terms"].map do |term|
      term if permitted_affiliations.include?(term["term"].to_sym)
    end.compact

    facets
  end

end

app/helpers/search_helper.rb
module SearchHelper

  def li_filter(title, type=nil)
    params_type = params['_type'].presence || 'all'
    active_class = ''
    if params_type == type
      active_class = 'active'
    end
    title = title.pluralize unless title == 'All'

    search_params = {'_type' => type}
    search_params[:q] = params[:q]
    if type == 'all' || type == 'person'
      search_params[:sort] = params[:sort]
      search_params[:affiliation] = params[:affiliation]
    end

    content_tag :li, class: "filter #{active_class}", 'data-type' => type do
      link_to title, search_path(search_params), remote: true
    end
  end

  def facet_url_params(group, facet)
    merged_facets = if facet_is_active?(group, facet)
      current_facets(group) - [facet['term']]
    else
      current_facets(group) | [facet['term']]
    end
    params.merge(group => merged_facets)
  end

  def result_object(es_result)
    SearchResult.new(es_result['_type'], es_result['_id'], es_result['_source'])
  end

  def result_url(search_result)
    if search_result.linkable?
      url_for controller: search_result.type.pluralize, action: 'show', id: (search_result.raw_data['slug'].presence || search_result.id)
    end
  end

  # If you are in a scope that would require you to login to see all results
  def in_private_scope
    params['_type'].blank? || params['_type'] == 'all' || params['_type'] == 'person'
  end


  def current_page
    (params[:page] || 1).to_i
  end
  def previous_page # we don't need to know the total_results for previous page
    current_page - 1 if current_page > 1
  end
  def next_page(total_results)
    current_page + 1 if current_page < total_results.to_i
  end

  def currently_showing(total_results)
    if total_results <= Settings.pagination_limit
      "all"
    else
      first = 1 + (current_page - 1) * Settings.pagination_limit
      last = [((first - 1) + Settings.pagination_limit), total_results].min
      "#{first} - #{last} of"
    end
  end

  def search_title
    title = ""
    title += "\"#{params[:q]}\" | Search " if params[:q].present?
    title += if !params[:_type] || params[:_type] == 'all'
      'All'
    elsif params[:_type] == 'department'
      'Offices & Services'
    else
      params[:_type].pluralize.titleize
    end
    title + " | Directory, Biola University"
  end

  def selected_sort(type)
    type = 'all' if type.blank?
    sort_options(type).select{|opt| opt[:param] == params[:sort]}.first.try(:[], :title) || sort_options(type).first.try(:[], :title)
  end

  def sort_options(type)
    type = 'all' if type.blank?
    options = []
    if type == 'all' || type == 'person'
      options << {title: 'Last Name', param: 'last_name'}
      options << {title: 'First Name', param: 'title'}
    end
    options
  end

private

  def facet_is_active?(group, facet)
    current_facets(group).include? facet['term']
  end

  def current_facets(group)
    params[group] || []
  end

  def param_facets
    params[:facets] || {}
  end
end

app/views/searches/_search_page.html.slim
= render 'shared/search_form'

.container
  #search_results
    = render 'search_results'

app/views/searches/_search_result.html.slim
.result_card data-profile-url=result_url(search_result)
  .padding
    - if search_result.data.image_url.present?
      .result_image
        = image_tag search_result.data.image_url
    - elsif calced_image = biola_person_image(search_result.raw_data['biola_id'])
      .result_image
        = image_tag calced_image


    .affiliations
      - visible_affiliations = search_result.affiliations.map(&:to_sym) & UserPermissables.new(current_user).affiliations
      - visible_affiliations.each do |aff|
        .label.label-default = aff.to_s.titleize


    .contact-titles
      .title = link_to_if search_result.linkable?, search_result.data.title, result_url(search_result), tabindex: index+1
      - search_result.data.subtitles.to_a.each do |subtitle|
        .subtitle = subtitle


    .contact-info
      - if search_result.data.email.present? && policy(Person).can_see_biola_email?
        div = mail_to search_result.data.email
      - if search_result.type == 'person'
        - if policy(Person).can_see_employee_phone? && search_result.data.phone.present?
          div = search_result.data.phone + ' (Direct)'
        - if policy(Person).can_see_alternate_phone? && search_result.data.alternate_phone.present?
          div = search_result.data.alternate_phone + ' (Alt)'
        - if policy(Person).can_see_student_mailbox? && search_result.raw_data['mailbox'].present?
          div Student Mailbox # #{search_result.raw_data['mailbox']}
      - elsif search_result.data.phone.present?
        div = search_result.data.phone

    .clearfix

app/views/searches/_search_results.html.slim
- if current_user.blank? && in_private_scope
  .alert.alert-info
    = fa_icon 'lock'
    span<> Not everyone in the directory is public. Please
    = link_to 'login', params_with({login: 'true'})
    span< to see more results.


- if params[:_type] == 'person' && (params[:affiliation] == 'faculty' || (params[:q].blank? && params[:affiliation] == nil))
  .callout-box Looking for the #{link_to('Faculty A-Z Page', faculty_index_url)}?


/ Don't show sort options on the department and group pages.
- unless params[:_type] == 'department' || params[:_type] == 'group'
  .sort_options.pull-right
    = ' Sort by '
    span.dropdown
      = link_to("#{selected_sort(params[:_type])} #{fa_icon('caret-down')}".html_safe, "#", "data-toggle"=>"dropdown")
      ul.dropdown-menu.pull-right role="menu" aria-labelledby="dLabel"
        - sort_options(params[:_type]).each do |option|
          li role="presentation" = link_to option[:title], params_with({sort: option[:param], page: nil})

/ Don't show filter options on the department and group pages.
- unless params[:_type] == 'department' || params[:_type] == 'group'
  .sort_options.pull-right
    span.dropdown
      = link_to("#{params[:affiliation].try(:titleize).presence || 'Filter'} #{fa_icon('caret-down')}".html_safe, "#", "data-toggle"=>"dropdown")
      ul.dropdown-menu.pull-right role="menu" aria-labelledby="dLabel"
        - if params[:affiliation].present?
          li role="presentation" = link_to "All", params_with({affiliation: nil})
        - UserPermissables.new(current_user).affiliations.map(&:to_s).sort.each do |affl|
          - unless affl == params[:affiliation]
            li role="presentation" = link_to affl.titleize, params_with({affiliation: affl, page: nil})

- if @results_count > 1
  p.results_count Showing #{currently_showing(@results_count)} #{@results_count} results
- elsif @results_count == 1
  p.results_count Showing only result
- else
  p.results_count There are no results matching your search

- @results.each_with_index do |es_result, index|
  = render 'search_result', search_result: result_object(es_result), index: index

ul.pager
  - if previous_page.present?
    li.previous = link_to 'Previous', params_with({page: previous_page})
  - if next_page(@pages_count).present?
    li.next = link_to 'Next', params_with({page: next_page(@pages_count)})

app/views/searches/landing.html.slim
#search_results_container
  = render 'shared/search_form'

  .container
    / #search_results needs to be here in case there is an error, this is what gets replaced.
    #search_results
      #landing_page
        .row
          .col-sm-6
            .title Biola University
            dl
              dt Address
              dd
                ' 13800 Biola Avenue
                br
                ' La Mirada, California 90639
              dt Phone
              dd = "(562) 903-6000"

          .col-sm-6
            .title Emergency Contact
            dl
              dt From off campus
              dd = "(562) 777-4000"
              dt From on campus
              dd x5111

app/views/searches/search.html.slim
/ Note, this is also updated in javascript when loading by ajax.
- content_for :title, search_title

#search_results_container = render 'search_page'

app/views/searches/search.js.erb
$("#search_results_container").html("<%= escape_javascript(render('search_page')) %>");

// Focus input field
focusSearch();