config/routes.rb
Directory::Application.routes.draw do

  resources :feedbacks, path: 'feedback', only: :create do
    get :thanks, on: :collection
  end
  resources :faculty, only: [:index]
  resources :people, only: [:show]
  resources :departments, path: 'offices-services', only: [:show]
  resources :groups, only: [:show]

  get "/search", to: "searches#search"
  get "/people" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'person'}).to_query}" }
  get "/departments" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'department'}).to_query}" }
  get "/offices-services" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'department'}).to_query}" }
  get "/groups" => redirect { |params, request| "#{ Rails.application.config.action_controller.relative_url_root }/search?#{request.params.merge({_type: 'group'}).to_query}" }


  root to: 'searches#landing'

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [200, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :logout

  # catch all so we can handle routing errors our own way.
  get "*path", to: "application#routing_error", via: :all
end

app/views/layouts/_account_list.html.slim
/ This file will provide the frontend toolkit with a dropdown list
/   if you are authenticated when you click the user icon in the top right.

- if current_user
  - content_for :account_list do
    - if my_profile = current_user.find_person
      li = link_to fa_icon("user", text: "My Profile"), my_profile
    li
      = link_to logout_path do
        i.fa.fa-power-off>
        | Logout

app/views/layouts/_feedback_form.html.slim
#report_problem
  a href="#" data-toggle="modal" data-target="#feedbackModal" Report a problem on this page

.modal.fade#feedbackModal
  .modal-dialog
    = form_tag :feedbacks, class: "modal-content" do
      .modal-header
        button type="button" class="close" data-dismiss="modal"
          span aria-hidden="true" &times;
          span class="sr-only" Close
        h4 Directory Feedback
      .modal-body
        .form-group
          label.required Problem or Feedback?
          = text_area_tag 'feedback', nil, class: 'form-control', required: true

        - if current_user
          = hidden_field_tag 'name', current_user.try(:name)
          = hidden_field_tag 'email', current_user.try(:email)

        - else
          .row
            .col-sm-6
              .form-group
                label.required Your Name
                = text_field_tag 'name', current_user.try(:name), class: 'form-control', required: true
            .col-sm-6
              .form-group
                label.required Your Email
                = text_field_tag 'email', current_user.try(:email), class: 'form-control', required: true

      .modal-footer
        button type="button" class="btn btn-default" data-dismiss="modal" Cancel
        button type="submit" class="btn btn-primary" Send

app/views/layouts/_global_search_form.html.slim
#global_search_form
  .search_form
    .search_input
      = fa_icon 'search'
      = form_tag search_path, method: :get do |f|
        = hidden_field_tag '_type', params['_type']
        = text_field_tag 'q', params[:q], placeholder: 'Search the directory...', tabindex: '1'

app/views/layouts/_meta_fields.html.slim
- if @meta_fields
  / meta name="title" content=@meta_fields.title   / title is handled in the application helper
  meta name="description" content=@meta_fields[:description]
  meta name="keywords" content=@meta_fields[:keywords]
  meta name="robots" content=@meta_fields[:robots]

  - if @meta_fields[:canonical_url].present?
    link rel="canonical" href=@meta_fields[:canonical_url]

app/views/layouts/_site_header.html.slim
.site-header
  .container
    - if content_for? :site_header
      = yield :site_header
    - else
      h2.page-title = link_to 'Directory', root_url

app/views/layouts/application.html.slim
doctype html
html lang="en-us"
  head
    / handles default html head tags and csrf_meta_tags
    = render 'frontend_toolkit/head', title: 'Directory, Biola University'
    = render 'layouts/meta_fields'
    = stylesheet_link_tag    "application", media: "all"

    / Load Proxima Nova and Minion Pro
    = javascript_include_tag '//use.typekit.net/zvt1wex.js'
    javascript:
      try{Typekit.load();}catch(e){}

  body class="#{controller_name} #{action_name}"

    / account_list must be before biola_header otherwise the list won't be defined in time.
    = render 'layouts/account_list'
    = render 'frontend_toolkit/biola_header', enable_auth: true

    = render 'layouts/site_header'
    #colorbar
    #body
      = yield

    - if current_user
        = render 'layouts/feedback_form'

    = render 'layouts/global_search_form'
    = render 'frontend_toolkit/global_marketing_footer'

    = javascript_include_tag "application"